package net.digitalswarm.popularmovies.data;


import android.arch.persistence.room.Entity;
import android.arch.persistence.room.Ignore;
import android.arch.persistence.room.PrimaryKey;
import net.digitalswarm.popularmovies.models.Movie;

@Entity(tableName = "favorites")
public class FavoriteMovie {

    private String movieTitle;
    private String moviePoster;
    private String movieRelease;
    private String movieRating;
    private String movieOverview;
    private String movieId;
    @PrimaryKey(autoGenerate = true)
    private int id;

    //constructor that parses a movie object and creates a favorite entry
    public FavoriteMovie(Movie favMovie) {
        this.movieTitle = favMovie.getOgName();
        this.moviePoster = favMovie.getPosterUrl();
        this.movieRelease = favMovie.getReleaseDate();
        this.movieRating = favMovie.getUserRating();
        this.movieOverview = favMovie.getPlotSynopsis();
        this.movieId = favMovie.getId();
    }

    //default constructor without autogenerated primary key 'id'
    @Ignore
    public FavoriteMovie(String movieTitle, String moviePoster, String movieRelease, String movieRating, String movieOverview, String movieId) {
        this.movieTitle = movieTitle;
        this.moviePoster = moviePoster;
        this.movieRelease = movieRelease;
        this.movieRating = movieRating;
        this.movieOverview = movieOverview;
        this.movieId = movieId;
    }

    public FavoriteMovie(String movieTitle, String moviePoster, String movieRelease, String movieRating, String movieOverview, String movieId, int id) {
        this.movieTitle = movieTitle;
        this.moviePoster = moviePoster;
        this.movieRelease = movieRelease;
        this.movieRating = movieRating;
        this.movieOverview = movieOverview;
        this.movieId = movieId;
        this.id = id;
    }


    public String getMovieTitle() {
        return movieTitle;
    }

    public void setMovieTitle(String movieTitle) {
        this.movieTitle = movieTitle;
    }

    public String getMoviePoster() {
        return moviePoster;
    }

    public void setMoviePoster(String moviePoster) {
        this.moviePoster = moviePoster;
    }

    public String getMovieRelease() {
        return movieRelease;
    }

    public void setMovieRelease(String movieRelease) {
        this.movieRelease = movieRelease;
    }

    public String getMovieRating() {
        return movieRating;
    }

    public void setMovieRating(String movieRating) {
        this.movieRating = movieRating;
    }

    public String getMovieOverview() {
        return movieOverview;
    }

    public void setMovieOverview(String movieOverview) {
        this.movieOverview = movieOverview;
    }

    public String getMovieId() {
        return movieId;
    }

    public void setMovieId(String movieId) {
        this.movieId = movieId;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }
}
